### ISSUE TITLE
Run Bloodhound with Podman

### ISSUE THREAD

**Issue by RobN007** [SySS-Research/Single-User-BloodHound#1]
Hello guys, 

i was looking for an alternative to docker desktop to run Bloodhound.
Found your projekt, but having problems to test it.

I installed Podman as it is the requirement (No dependencies except for podman (and bash, grep and date)!)

But i am not exactly sure how i do the step: Simply run ./bloodhound-su

Could you pleae help me out what i need to do exactly ?

thank you for your work & help

**Comment by AdrianVollmer** [comment]
Just go into a command line, clone this repository, change to the right directory, and enter `./bloodhound-ce`. (Note: the command changed.) If you have issues with any of those steps, I suggest asking ChatGPT or so. It's pretty basic stuff. Hope that helps!
